swagger: "2.0"
info:
  title: "Gas Include"
  description: "Gas Include"
  version: "1.0.0"
host: "public.endpoints.gas-include.cloud.goog"
basePath: "/"
schemes:
  - "https"
paths:
  "/hello":
    get:
      description: "database test url"
      operationId: "hello"
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The IATA code is invalid or missing."
  "/echo":
    get:
      description: "This is a test endpoint."
      operationId: "echo"
      parameters:
        -
          name: param
          in: query
          required: false
          type: string
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "Error."
